### ISSUE TITLE
Additional event binding - hover

### ISSUE THREAD

**Issue by robertjwozniak** [robertjwozniak/fire-up#10]
We need to add another additional event binding. We need the user to be able to trigger hover on the specific element. 
Guidelines:
`fire-role={ "event" : "hover" }`
When attaching an event to the element, please instead of using "hover" on addEventListener binding, use "mouseenter" or "mouseover". Which is going to help us to keep good performance.

**Comment by LucasRafaelCipriani** [comment]
@robertjwozniak I need you help. My saves aren't being applied in the page.

**Comment by robertjwozniak** [comment]
Okay. Did you use `webpack --watch` command and `webpack-dev-server --watch`? If you don't use those commands, the changes will not be applied, because it will not merge all of the code into one build.

**Comment by LucasRafaelCipriani** [comment]
I used the command ` webpack --watch` but I receive an error message saying that I need to install the webpack-CLI or the webpack-command. I tried to install these programs but I'm receiving an error. Do you have some idea of why it is happening? 
The command `webpack-dev-server --watch` worked.

**Comment by robertjwozniak** [comment]
Okay. That's why it's not applying your changes because the command `webpack --watch` has to be executed. Let me check that.

**Comment by robertjwozniak** [comment]
Okay. I've got the solution. I received the same error as you did. 
I'm going to write below a list of necessary steps to fix it:

1. Remove global installation of webpack - npm remove -g webpack
2. From the local folder of fire-up project remove 'node_modules' folder
3. After removing above folder, please enter the console and make sure that you are in the 'fire-up' folder.
4. Execute - npm install
5. After finishing above operation, in the console, you need to type - npm run-script build
6. And - webpack-dev-server --watch

Above steps should resolve the issue. Once you run 'npm run-script build' it will execute 'webpack --watch' and your changes will be reflecting again.

**Comment by robertjwozniak** [comment]
Could you do it @LucasRafaelCipriani ?

**Comment by LucasRafaelCipriani** [comment]
@robertjwozniak  I have tried to follow these steps, but in the 5th step, I received an error.
This is the error that I received.
![image](https://user-images.githubusercontent.com/18601782/42139230-26c2e488-7d60-11e8-9073-89e74e7c7b52.png)

**Comment by robertjwozniak** [comment]
Can you show me your package.json file?

**Comment by LucasRafaelCipriani** [comment]
`{
  "name": "fire-up.js",
  "version": "0.0.1",
  "description": "Fire-up.js is a small and fast framework for building user interfaces.",
  "main": "app.js",
  "start": "index.html",
  "scripts": {
    "start": "webpack-dev-server --watch",
    "build": "webpack --watch",
    "babel": "babel --presets es2015 /app/js/index.js -o build/app.bundle.js"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/robertjwozniak/fire-up.git"
  },
  "keywords": [
    "user-interfaces",
    "framework",
    "js"
  ],
  "author": "Robert Wozniak",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/robertjwozniak/fire-up/issues"
  },
  "homepage": "https://github.com/robertjwozniak/fire-up#readme",
  "dependencies": {
    "babel": "^6.23.0",
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.4",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.24.1",
    "path": "^0.12.7",
    "require": "^2.4.20",
    "webpack": "^3.11.0"
  },
  "devDependencies": {
    "uglifyjs-webpack-plugin": "^1.2.4",
    "webpack-cli": "^3.0.8",
    "webpack-command": "^0.3.1",
    "webpack-dev-server": "^2.11.2"
  }
}
`

**Comment by LucasRafaelCipriani** [comment]
`{
  "name": "fire-up.js",
  "version": "0.0.1",
  "description": "Fire-up.js is a small and fast framework for building user interfaces.",
  "main": "app.js",
  "start": "index.html",
  "scripts": {
    "start": "webpack-dev-server --watch",
    "build": "webpack --watch",
    "babel": "babel --presets es2015 /app/js/index.js -o build/app.bundle.js"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/robertjwozniak/fire-up.git"
  },
  "keywords": [
    "user-interfaces",
    "framework",
    "js"
  ],
  "author": "Robert Wozniak",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/robertjwozniak/fire-up/issues"
  },
  "homepage": "https://github.com/robertjwozniak/fire-up#readme",
  "dependencies": {
    "babel": "^6.23.0",
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.4",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.24.1",
    "path": "^0.12.7",
    "require": "^2.4.20",
    "webpack": "^3.11.0"
  },
  "devDependencies": {
    "uglifyjs-webpack-plugin": "^1.2.4",
    "webpack-cli": "^3.0.8",
    "webpack-command": "^0.3.1",
    "webpack-dev-server": "^2.11.2"
  }
}
`

**Comment by robertjwozniak** [comment]
@LucasRafaelCipriani 
Okay. hit npm update. And afterwards, check the version of webpack.
Should be 3.12

**Comment by robertjwozniak** [comment]
If npm update doesn't change the version of webpack. Open package.json and change the version manually to 3.12 and hit npm install.

**Comment by LucasRafaelCipriani** [comment]
@robertjwozniak Now it is working!!! Thanks a lot. Now I can make progress in the development.

**Comment by robertjwozniak** [comment]
Done.
