### ISSUE TITLE
Bug: While performing binding action event listeners go up

### ISSUE THREAD

**Issue by robertjwozniak** [robertjwozniak/fire-up#21]
In the beginning, before you start performing binding actions our number of listeners is 17 and it should stay that way.
When you start performing binding actions on inputs or somewhere else it raises up immediately. 
We need to kill it.
![image](https://user-images.githubusercontent.com/16007466/42644218-66fed114-85d1-11e8-9978-158943bfc607.png)

**Comment by LucasRafaelCipriani** [comment]
![capturar](https://user-images.githubusercontent.com/18601782/43020303-f4cfb886-8c35-11e8-94f8-789d61726c2b.PNG)

**Comment by LucasRafaelCipriani** [comment]
@robertjwozniak

**Comment by robertjwozniak** [comment]
Event listeners stay still, don't even move during the whole process of testing.
![image](https://user-images.githubusercontent.com/16007466/45929749-44e31880-bf2c-11e8-8775-cbb78e40c073.png)

I can see some memory spikes from time to time, I will be investigating it further in some time.
