### ISSUE TITLE
Implementation: If bindings

### ISSUE THREAD

**Issue by robertjwozniak** [robertjwozniak/fire-up#28]
We need to create if bindings.
More info soon.

**Comment by robertjwozniak** [comment]
Basically,
![image](https://user-images.githubusercontent.com/16007466/43196455-4b369842-8fde-11e8-9fc8-645f9eb9cc53.png)
Our binding will be called "fire-if"
Let me know your doubts.

**Comment by LucasRafaelCipriani** [comment]
@robertjwozniak  I managed to implement the if binding, but it is working just with certain variables like: menuList, but it is not working with other properties like: text-one. You can take a look to check if the implementation is correct.

**Comment by robertjwozniak** [comment]
Hey @LucasRafaelCipriani ,
New bindings implementation has been done. Can you re-implement "fire-if" bindings once again and do pull request, please?

!!! Thanks!!!

**Comment by robertjwozniak** [comment]
Ah, please remember that implementation of this binding has to work with collectedBindings as well.

**Comment by robertjwozniak** [comment]
@LucasRafaelCipriani How is it going? Are you going to do the pull request?
@jennifertakagi will have to start her task.

**Comment by robertjwozniak** [comment]
Done.
@jennifertakagi You can start your task.
