### ISSUE TITLE
Bug: Fire-if pipeline is not applying a default property.

### ISSUE THREAD

**Issue by robertjwozniak** [robertjwozniak/fire-up#70]
If the pipeline property wasn't provided by the developer, the default value of visible should be applied. Instead, we're receiving an error.
![image](https://user-images.githubusercontent.com/16007466/45931892-014bd700-bf4b-11e8-9922-9f668c4fc528.png)

``` HTML
<div fire-if="array.length > 0 && textOne.length > 1">
   <p>Testing visible</p>
</div>
```

In that case above code should evaluate in the following order: if array.length is higher than zero and textOne length is higher than one, make the element visible. Otherwise, if one of the statements is false, the element should not appear, because of default pipeline parameter visible, if an expression evaluates to false, it implies that the element should disappear.

**Comment by robertjwozniak** [comment]
@jennifertakagi Once you've got a little bit of time, please take a look at it.

**Comment by jennifertakagi** [comment]
@robertjwozniak all right, done, I'm creating the pull request.

**Comment by robertjwozniak** [comment]
@jennifertakagi I have tested and it's not working properly.

**Comment by robertjwozniak** [comment]
``` HTML
<input fire-if="array.length === 0 | disabled" type="text">
```
I have applied above line and array was containing one element, instead of having input visible but not disabled, the input has disappeared.

**Comment by jennifertakagi** [comment]
Right, Robert!! Fixed.
