### ISSUE TITLE
Planning session - Refactoring, feature releases, etc.

### ISSUE THREAD

**Issue by robertjwozniak** [robertjwozniak/fire-up#77]
Hi everybody,

I want to come back to the development of the framework, but it seems like some parts of the framework will have to be changed. The project is not over. 

Have you got 30 minutes to spare this Saturday, 6th of April? 
@LucasRafaelCipriani 
@matheeeusl 
@jennifertakagi 

Please, if you do, can you give me your timeslot? Would be fantastic, if we can have a voice call over Google hangouts and chat for a little bit about the project and what is going to change and also we might get rid of at least half of the framework and write it in a better, modern way.

Let me know if you're willing to have an initial call.

Cheers

**Comment by jennifertakagi** [comment]
Hi Robert !!
Last week I was visiting this project and wondering if it was alive haha
This Saturday I will be back from a trip, so I can join this call any day after that :)

Cheers

**Comment by LucasRafaelCipriani** [comment]
Hey Robert!! I can join this call in this Saturday. I think for me would be better at afternoon.

**Comment by robertjwozniak** [comment]
Fantastic, good to hear from you chaps. 
What about @matheeeusl ?

**Comment by robertjwozniak** [comment]
We've got 4 hours of the timezone difference. I think we will sort it out in the other day.
I'll let you know in the upcoming week, and we will schedule some specific time to do it when everyone is available.

**Comment by robertjwozniak** [comment]
Sorry chaps, I've got stuff going on, I've got to finish it first, and I'll let you know when I'm going to be able to spare some time for the project.

**Comment by jennifertakagi** [comment]
Hi Robert, okay, I will wait :)
